//
// Created by pcvii on 4/3/2023.
//

#ifndef OPENVIII_CPP_WIP_MAGICSPELL_HPP
#define OPENVIII_CPP_WIP_MAGICSPELL_HPP
#include <cstdint>
namespace open_viii::kernel {
enum class MagicSpell : std::uint8_t
{
  None        = 0,
  Fire        = 1,
  Fira        = 2,
  Firaga      = 3,
  Blizzard    = 4,
  Blizzara    = 5,
  Blizzaga    = 6,
  Thunder     = 7,
  Thundara    = 8,
  Thundaga    = 9,
  Water       = 10,
  Aero        = 11,
  Bio         = 12,
  Demi        = 13,
  Holy        = 14,
  Flare       = 15,
  Meteor      = 16,
  Quake       = 17,
  Tornado     = 18,
  Ultima      = 19,
  Apocalypse  = 20,
  Cure        = 21,
  Cura        = 22,
  Curaga      = 23,
  Life        = 24,
  FullLife    = 25,
  Regen       = 26,
  Esuna       = 27,
  Dispel      = 28,
  Protect     = 29,
  Shell       = 30,
  Reflect     = 31,
  Aura        = 32,
  Double      = 33,
  Triple      = 34,
  Haste       = 35,
  Slow        = 36,
  Stop        = 37,
  Blind       = 38,
  Confuse     = 39,
  Sleep       = 40,
  Silence     = 41,
  Break       = 42,
  Death       = 43,
  Drain       = 44,
  Pain        = 45,
  Berserk     = 46,
  Float       = 47,
  Zombie      = 48,
  Meltdown    = 49,
  Scan        = 50,
  FullCure    = 51,
  Wall        = 52,
  Rapture     = 53,
  Percent     = 54,
  Catastrophe = 55,
  TheEnd      = 56,
  // For drawing Guardian Forces.
  Quezacotl   = 64,
  Shiva       = 65,
  Ifrit       = 66,
  Siren       = 67,
  Brothers    = 68,
  Diablos     = 69,
  Carbuncle   = 70,
  Leviathan   = 71,
  Pandemona   = 72,
  Cerberus    = 73,
  Alexander   = 74,
  Doomtrain   = 75,
  Bahamut     = 76,
  Cactuar     = 77,
  Tonberry    = 78,
  Eden        = 79,
};
}// namespace open_viii::kernel
#endif// OPENVIII_CPP_WIP_MAGICSPELL_HPP
