// This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
#ifndef VIIIARCHIVE_UNLOCKERT_HPP
#define VIIIARCHIVE_UNLOCKERT_HPP
namespace open_viii::kernel {
/**
 * @see
 * https://github.com/DarkShinryu/doomtrain/wiki/Junctionable-Abilities-Unlocker
 * @see
 * https://github.com/alexfilth/doomtrain/blob/master/Doomtrain/MainForm.Designer.cs
 */
enum class UnlockerT : std::uint8_t
{
  none,
  gf_level1,
  gf_level2,
  gf_level3,
  gf_level4,
  gf_level5,
  gf_level6,
  gf_level7,
  gf_level8,
  gf_level9,
  gf_level10,
  gf_level11,
  gf_level12,
  gf_level13,
  gf_level14,
  gf_level15,
  gf_level16,
  gf_level17,
  gf_level18,
  gf_level19,
  gf_level20,
  gf_level21,
  gf_level22,
  gf_level23,
  gf_level24,
  gf_level25,
  gf_level26,
  gf_level27,
  gf_level28,
  gf_level29,
  gf_level30,
  gf_level31,
  gf_level32,
  gf_level33,
  gf_level34,
  gf_level35,
  gf_level36,
  gf_level37,
  gf_level38,
  gf_level39,
  gf_level40,
  gf_level41,
  gf_level42,
  gf_level43,
  gf_level44,
  gf_level45,
  gf_level46,
  gf_level47,
  gf_level48,
  gf_level49,
  gf_level50,
  gf_level51,
  gf_level52,
  gf_level53,
  gf_level54,
  gf_level55,
  gf_level56,
  gf_level57,
  gf_level58,
  gf_level59,
  gf_level60,
  gf_level61,
  gf_level62,
  gf_level63,
  gf_level64,
  gf_level65,
  gf_level66,
  gf_level67,
  gf_level68,
  gf_level69,
  gf_level70,
  gf_level71,
  gf_level72,
  gf_level73,
  gf_level74,
  gf_level75,
  gf_level76,
  gf_level77,
  gf_level78,
  gf_level79,
  gf_level80,
  gf_level81,
  gf_level82,
  gf_level83,
  gf_level84,
  gf_level85,
  gf_level86,
  gf_level87,
  gf_level88,
  gf_level89,
  gf_level90,
  gf_level91,
  gf_level92,
  gf_level93,
  gf_level94,
  gf_level95,
  gf_level96,
  gf_level97,
  gf_level98,
  gf_level99,
  gf_level100,
  ability1,
  ability2,
  ability3,
  ability4,
  ability5,
  ability6,
  ability7,
  ability8,
  ability9,
  ability10,
  ability11,
  ability12,
  ability13,
  ability14,
  ability15,
  ability16,
  ability17,
  ability18,
  ability19,
  ability20,
  ability21,
};
}// namespace open_viii::kernel
#endif// VIIIARCHIVE_UNLOCKERT_HPP
