version: 2

sphinx:
  configuration: raw_docs/source/conf.py

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: raw_docs/source/requirements.txt
