stages:
  - build

jobs:
  include:
  
    # Linux
    - stage: build
      language: cpp
      compiler:
        #- clang
        - gcc
      os:
        - linux
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10.2.1
            env:
         - MATRIX_EVAL="CC=gcc-10.2.1 && CXX=g++-10.2.1"
      before_install:
        - sudo apt-get -y install ninja-build libomp-dev
        - pip install cmake
      script:
        # Build
        - cmake --version; cmake --log-level=VERBOSE -G "Ninja Multi-Config" -B build; ninja -j12 -C build
        - ninja -j12 -C build -f build-Release.ninja
        # Tests
        - cd build; ctest -j12 -C Debug ## -VV
      branches:
        only:
          - main
