version: 1.0.{build}
skip_commits:
  message: /UPDATE_DOCS/      # Regex for matching commit message
environment:
  matrix:
    - job_name: Windows MSVC build
      appveyor_build_worker_image: Visual Studio 2022

cache:
  - c:\vcpkg

init:
  - cmd: >-
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"

      git clone https://github.com/microsoft/vcpkg c:\vcpkg

      c:\vcpkg\bootstrap-vcpkg.bat

      set VCPKG_DEFAULT_TRIPLET=x64-windows

build_script:
  - cmd: >-
      cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -B build -DCMAKE_TOOLCHAIN_FILE=c:\vcpkg\scripts\buildsystems\vcpkg.cmake .

      cmake --build build

test_script:
  - cmd:
      cd build

      ctest -C debug --extra-verbose

      cd ..

artifacts:
  - path: 'bin/*.exe'
    name: Canary

deploy:
  - provider: GitHub
    release: Canary
    description: Automatic Test build version($(APPVEYOR_BUILD_VERSION)). [Documentation](https://sebanisu.github.io/OpenVIII_CPP_WIP/applications.html#)
    auth_token:
      secure: 5giEwDYEP975x3C+JYDNGukTupBCPcmez7GbulvUX40/2C5cgs5ta8Gyq6IYpFmW
    artifact: Canary
    prerelease: true
    force_update: true